version: '3.1.4'
services:
  db:
    image: mysql:8.0.13
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AmusementParkDB
      SPRING_DATABASE_URL: jdbc:mysql://mysql:3306/MYSQL_DATABASE
      SPRING_DATABASE_USERNAME: root
      SPRING_DATABASE_PASSWORD: root
    ports:
      - 3306:3306